<?php
/**
 * @category  Magebuzz
 * @package   Magebuzz_Gallerymedia
 * @version   0.1.6
 * @copyright Copyright (c) 2012-2015 http://www.magebuzz.com
 * @license   http://www.magebuzz.com/terms-conditions/
 * @var $this Magebuzz_Gallerymedia_Block_List
 */
?>
<?php
  if (!$this->getCollection()->getSize()) {
    $album_id = $this->getParentBlock()->getAlbumId();
    $collection = Mage::getModel('gallerymedia/galleryitems')->getCollection()
      ->addFieldToFilter('status', '1');
    $collection->getSelect()
      ->distinct()
      ->join(array('media_album' => Mage::getSingleton('core/resource')->getTableName('gallery_album_entity_item')), 'media_album.gallery_item_id=main_table.gallery_item_id');
    $collection->addFieldToFilter('gallery_album_id', $album_id);
    $collection->getSelect()->order('sort_order', 'ASC');
    $this->setCollection($collection);
  }

 ?>
<script type="text/javascript">
  $popup(document).ready(function () {
    $popup(".venture_spring_popup").fancybox();
  });
</script>
<?php $_galleryHelper = Mage::helper('gallerymedia'); ?>
<?php $boxSizeConfig = Mage::getStoreConfig('gallerymedia/media_setting/media_box_size'); ?>
<?php $boxSize = $_galleryHelper->getConfigSize($boxSizeConfig); ?>
<?php $collection = $this->getCollection(); ?>
<?php if ($collection->getSize()): ?>
  <div class="gallery">
  <?php echo $this->getToolbarHtml(); ?>
  <?php $_columnCount = 4; ?>
  <?php if ($this->getMode() == 'grid'): ?> <?php // Grid Mode ?>
    <div class="list-items">
      <?php $i = 0;
      foreach ($collection as $_item): ?>
        <?php if ($i++ % $_columnCount == 0): ?>
          <ul class="media-grid">
        <?php endif ?>
        <?php if ($_item->getMediaType() == '2'): ?>
        <?php $filename = $_item->getItemFile(); ?>
        <?php $videoURL = $_item->getVideoUrl(); ?>
        <?php if ($videoURL) $videoId = $_galleryHelper->getYouTubeIdFromURL($videoURL); ?>
        <?php endif; ?>
        <li
          class="<?php if ($_item->getMediaType() == '2'): ?>video<?php else: ?>photo<?php endif; ?><?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
          <div class="media-image">
            <?php if ($_item->getMediaType() == '2'): ?>
              <?php if ($_galleryHelper->isPreviewVideo()): ?>
                <div id="popup_video_<?php echo $_item->getId(); ?>" style="display:none;">
                  <div id="popup_container_<?php echo $_item->getId(); ?>"
                       style="display: none;">Loading the player ...</div>
                  <script type="text/javascript">
                    jwplayer("popup_container_<?php echo $_item->getId(); ?>").setup({
                      flashplayer: "<?php echo $this->getJsUrl('magebuzz/gallerymedia/player.swf')?>",
                      file: "<?php if($videoURL != ''):?>http://www.youtube.com/watch?v=<?php echo $videoId?><?php else:?><?php echo Mage::getBaseUrl('media')."gallerymedia/mediafile/".$filename?><?php endif;?>",
                      controlbar: "over",
                      height: 320,
                      width: 400
                    });
                  </script>
                </div>
                <div class="video-thumbnail" <?php if ($this->getSizeHtml()) {
                  echo $this->getSizeHtml();
                } else {
                  echo 'style="width:200px;height:200px;"';
                } ?>>
                  <p <?php if ($this->getSizeHtml()) {
                    echo $this->getSizeHtml();
                  } else {
                    echo 'style="width:200px;height:200px;"';
                  } ?>>
                    <a class="venture_spring_popup" data-fancybox-group="gallery"
                       href="#popup_video_<?php echo $_item->getId(); ?>"
                       title="<?php echo $_item->getItemName(); ?>">
                      <?php $video_thumbnail = Mage::helper("gallerymedia/image")->init($_item)->resize($_item['media_thumbnail'], $boxSize[0], $boxSize[1], 'thumbnail'); ?>
                      <img src="<?php echo $video_thumbnail; ?>"
                           title="<?php echo $_item->getItemName(); ?>"
                           alt="<?php echo $_item->getItemName(); ?>" align="left"/>
                    </a>
                  </p>
                </div>
                <div class="icon"><img
                    src="<?php echo $this->getSkinUrl('magebuzz/gallerymedia/images//video_icon.png') ?>"/>
                </div>
              <?php else: ?>
                <div class="video-thumbnail" <?php if ($this->getSizeHtml()) {
                  echo $this->getSizeHtml();
                } else {
                  echo 'style="width:200px;height:200px;"';
                } ?>>
                  <p <?php if ($this->getSizeHtml()) {
                    echo $this->getSizeHtml();
                  } else {
                    echo 'style="width:200px;height:200px;"';
                  } ?>>
                    <a class="venture_spring_popup" data-fancybox-group="gallery"
                       href="<?php echo $this->getItemUrl($_item->getGalleryItemId()) ?>"
                       title="<?php echo $_item->getItemName(); ?>">
                      <?php $video_thumbnail = Mage::helper("gallerymedia/image")->init($_item)->resize($_item['media_thumbnail'], $boxSize[0], $boxSize[1], 'thumbnail'); ?>
                      <img src="<?php echo $video_thumbnail; ?>"
                           title="<?php echo $_item->getItemName(); ?>"
                           alt="<?php echo $_item->getItemName(); ?>" align="left"/>
                    </a>
                  </p>
                </div>
                <div class="icon"><img
                    src="<?php echo $this->getSkinUrl('magebuzz/gallerymedia/images/video_icon.png') ?>"/>
                </div>
              <?php endif; ?>
            <?php else: ?>
              <!-- image type -->
              <div class="media-photo" <?php if ($this->getSizeHtml()) {
                echo $this->getSizeHtml();
              } else {
                echo 'style="width:200px;height:200px;"';
              } ?>>
                <p <?php if ($this->getSizeHtml()) {
                  echo $this->getSizeHtml();
                } else {
                  echo 'style="width:200px;height:200px;"';
                } ?>>
                  <?php $imageUrlInit = Mage::helper("gallerymedia/image")->getImageUrl($_item->getItemFile()); ?>
                  <a <?php if ($_galleryHelper->isPreviewVideo()): ?>  class="venture_spring_popup" data-fancybox-group="gallery"  href="<?php echo $imageUrlInit; ?>" <?php else : ?>href="<?php echo $this->getItemUrl($_item->getGalleryItemId()) ?>" <?php endif ?>
                    title="<?php echo $_item->getItemName(); ?>">
                    <?php $image_url = Mage::helper("gallerymedia/image")->init($_item)->resize($_item['item_file'], $boxSize[0], $boxSize[1]); ?>
                    <img src="<?php echo $image_url; ?>"
                         title="<?php echo $_item->getItemName(); ?>"
                         alt="<?php echo $_item->getItemName(); ?>" align="left"/>
                  </a>
                </p>
              </div>
              <div class="icon"><img
                  src="<?php echo $this->getSkinUrl('magebuzz/gallerymedia/images//photo_icon.png') ?>"/>
              </div>
            <?php endif; ?>
          </div>
          <?php if ($_galleryHelper->showMediaTitle()): ?>
            <div class="media-name" style="width:<?php echo $boxSize[0] + 30 ?>px">
              <a href="<?php echo $this->getItemUrl($_item->getGalleryItemId()) ?>"
                 title="<?php echo $_item->getItemName(); ?>">
                <?php echo $_item->getItemName(); ?>
              </a>
              <?php if ($_galleryHelper->showUpdateDate()): ?>
                <div class="clear"></div>
                <?php $updateTime = new DateTime($_item->getUpdateTime()); ?>
                <span class="updateTime"><?php echo date_format($updateTime, "F j, Y") ?></span>
              <?php endif; ?>
            </div>
          <?php endif; ?>
          <?php if ($_galleryHelper->getReviewCount($_item->getGalleryItemId()) > 0): ?>
            <div class="ratings">
              <div class="rating-box">
                <div
                  style="width:<?php echo Mage::helper('gallerymedia')->getRatingSummary($_item->getGalleryItemId()) ?>%"
                  class="rating"></div>
              </div>
            </div>
          <?php endif ?>
        </li>
        <?php if ($i % $_columnCount == 0 || $i == count($collection)): ?>
          </ul>
        <?php endif ?>
      <?php endforeach; ?>
      </ul>
    </div>
  <?php else: ?>

    <!--List Mode-->

    <ul class="media-list">
      <?php $i = 0;
      foreach ($collection as $_item): ?>
        <li class="<?php if ($_item->getMediaType() == '2'): ?>video<?php else: ?>photo<?php endif; ?>">
          <div class="col-1">
            <?php $filename = $_item->getItemFile(); ?>
            <?php $videoURL = $_item->getVideoUrl(); ?>
            <?php if ($videoURL) $videoId = $_galleryHelper->getYouTubeIdFromURL($videoURL); ?>
            <div class="media-image">
              <?php if ($_item->getMediaType() == '2'): ?>
                <?php if ($_galleryHelper->isPreviewVideo()): ?>
                  <div id="popup_video_<?php $_item->getId(); ?>" style="display:none;">
                    <div id="popup_container_<?php echo $i ?>"
                         style="display: none;">Loading the player ...</div>
                    <script type="text/javascript">
                      jwplayer("popup_container_<?php echo $i?>").setup({
                        flashplayer: "<?php echo $this->getJsUrl('magebuzz/gallerymedia/player.swf')?>",
                        file: "<?php if($videoURL != ''):?>http://www.youtube.com/watch?v=<?php echo $videoId?><?php else:?><?php echo Mage::getBaseUrl('media')."gallerymedia/mediafile/".$filename?><?php endif;?>",
                        controlbar: "over",
                        height: 320,
                        width: 400
                      });
                    </script>
                  </div>
                  <div class="video-thumbnail" <?php if ($this->getSizeHtml()) {
                    echo $this->getSizeHtml();
                  } else {
                    echo 'style="width:200px;height:200px;"';
                  } ?>>
                    <p <?php if ($this->getSizeHtml()) {
                      echo $this->getSizeHtml();
                    } else {
                      echo 'style="width:200px;height:200px;"';
                    } ?>>
                      <a class="venture_spring_popup" data-fancybox-group="gallery"
                         href="#popup_video_<?php $_item->getId(); ?>"
                         title="<?php echo $_item->getItemName(); ?>">
                        <?php $video_thumbnail = Mage::helper("gallerymedia/image")->init($_item)->resize($_item['media_thumbnail'], $boxSize[0], $boxSize[1], 'thumbnail'); ?>
                        <img width="<?php echo $boxSize[0] ?>"
                             height="<?php echo $boxSize[1] ?>"
                             src="<?php echo $video_thumbnail; ?>"
                             title="<?php echo $_item->getItemName(); ?>"
                             alt="<?php echo $_item->getItemName(); ?>" align="left"/>
                      </a>
                    </p>
                  </div>
                  <div class="icon"><img
                      src="<?php echo $this->getSkinUrl('magebuzz/gallerymedia/images//video_icon.png') ?>"/>
                  </div>
                <?php else: ?>
                  <div class="video-thumbnail" <?php if ($this->getSizeHtml()) {
                    echo $this->getSizeHtml();
                  } else {
                    echo 'style="width:200px;height:200px;"';
                  } ?>>
                    <p <?php if ($this->getSizeHtml()) {
                      echo $this->getSizeHtml();
                    } else {
                      echo 'style="width:200px;height:200px;"';
                    } ?>>
                      <a class="venture_spring_popup" data-fancybox-group="gallery"
                         href="<?php echo $this->getItemUrl($_item->getGalleryItemId()) ?>"
                         title="<?php echo $_item->getItemName(); ?>">
                        <?php $video_thumbnail = Mage::helper("gallerymedia/image")->init($_item)->resize($_item['media_thumbnail'], $boxSize[0], $boxSize[1], 'thumbnail'); ?>
                        <img width="<?php echo $boxSize[0] ?>"
                             height="<?php echo $boxSize[1] ?>"
                             src="<?php echo $video_thumbnail; ?>"
                             title="<?php echo $_item->getItemName(); ?>"
                             alt="<?php echo $_item->getItemName(); ?>" align="left"/>
                      </a>
                    </p>
                  </div>
                  <div class="icon"><img
                      src="<?php echo $this->getSkinUrl('magebuzz/gallerymedia/images//video_icon.png') ?>"/>
                  </div>
                <?php endif; ?>
              <?php else: ?>
                <div class="media-photo" <?php if ($this->getSizeHtml()) {
                  echo $this->getSizeHtml();
                } else {
                  echo 'style="width:200px;height:200px;"';
                } ?>>
                  <p <?php if ($this->getSizeHtml()) {
                    echo $this->getSizeHtml();
                  } else {
                    echo 'style="width:200px;height:200px;"';
                  } ?>>
                    <?php
                    $imageUrlInit = Mage::helper("gallerymedia/image")->getImageUrl($_item->getItemFile());
                    ?>
                    <a <?php if ($_galleryHelper->isPreviewVideo()): ?>  class="venture_spring_popup" data-fancybox-group="gallery"  href="<?php echo $imageUrlInit; ?>" <?php else : ?>href="<?php echo $this->getItemUrl($_item->getGalleryItemId()) ?>" <?php endif ?>
                      title="<?php echo $_item->getItemName(); ?>">
                      <?php
                      $image_url = Mage::helper("gallerymedia/image")->init($_item)->resize($_item['item_file'], $boxSize[0], $boxSize[1]);
                      ?>
                      <img src="<?php echo $image_url; ?>"
                           title="<?php echo $_item->getItemName(); ?>"
                           alt="<?php echo $_item->getItemName(); ?>" align="left"/>
                    </a>
                  </p>
                </div>
                <div class="icon"><img
                    src="<?php echo $this->getSkinUrl('magebuzz/gallerymedia/images//photo_icon.png') ?>"/>
                </div>
              <?php endif; ?>
            </div>
          </div>
          <div class="col-2">
            <?php if ($_galleryHelper->showMediaTitle()): ?>
              <div class="media-name">
                <a href="<?php echo $this->getItemUrl($_item->getGalleryItemId()) ?>"
                   title="<?php echo $_item->getItemName(); ?>">
                  <?php echo $_item->getItemName(); ?>
                </a>
              </div>
            <?php endif ?>
            <?php if ($_galleryHelper->showUpdateDate()): ?>
              <?php $updateTime = new DateTime($_item->getUpdateTime()); ?>
              <span class="updateTime"><?php echo date_format($updateTime, "F j, Y") ?></span>
            <?php endif; ?>
            <?php if ($_galleryHelper->getReviewCount($_item->getGalleryItemId()) > 0): ?>
              <div class="ratings">
                <div class="rating-box">
                  <div
                    style="width:<?php echo Mage::helper('gallerymedia')->getRatingSummary($_item->getGalleryItemId()) ?>%"
                    class="rating"></div>
                </div>
              </div>
            <?php endif ?>
            <?php if ($_galleryHelper->showMediaDescription()): ?>
              <div class="media-description">
															<?php echo $_item->getItemDescription() ?>
													</div>
            <?php endif ?>
          </div>
        </li>
      <?php endforeach; ?>
    </ul>
  <?php endif; ?>
  <?php echo $this->getToolbarHtml(); ?>
  </div>
<?php else: ?>
  <p class="note-msg"><?php echo $this->__('There are no media item') ?></p>
<?php endif; ?>
